### ISSUE TITLE
List of scored genome wide missense pathogenicity predictions with UNET?

### ISSUE THREAD

**Issue by ggstatgen** [allydunham/sequence_unet#1]
Hi

I have read the interesting preprint and was wondering if the tool is suitable for germline missense SNP pathogenicity prediction labelling. We currently use primateAI (for all protein coding genes) and EVE (if available) scores but would be interested in one comprehensive method. We use these missense predictions alongside LOF predictions obtained with VEP/loftee to perform rare variant burden tests in large genotype/phenotype cohorts.

If so, is there a dataset of UNET genome wide coding scores that can be downloaded?
If not, will UNET missense pathogenicity prediction scores be available via VEP/Ensembl or any other channel in the future? 

Many thanks in any case.

**Comment by allydunham** [comment]
I think the model could be used for SNP pathogenicity prediction, although I would recomend benchmarking it against some SNPs you know are pathogenic/not to be sure. I think the finetuned pathogenicity or pathogenicity top models would be the most appropriate there (coded "patho_finetune" and "patho_top" if you use the package). You could test the different models to see what is best for your application though.

We don't currently have any pre-calculated score available, partly because the model aims to be fast and easy to run and partly because it hasn't been fully published yet. I could generate predictions for some key organisms easily if there is interest though, which would likely be available as a direct download rather than through VEP or ensembl.

A few things to bear in mind:

- The model only works for protien coding genes.
- The model works best on proteins with known structure, even if that information is not directly utilised, because they made up the training set.
- It seems to have broadly similar performance to EVE on structured protein pathogenicity predicion but is a bit worse on proteins without known structure. There's a similar result for PrimateAI, but with more clearly better results on structured proteins (see figure 4 of the pre-print). I haven't tested performance of EVE or other predictors on structured vs non-structured proteins so it is possible they are simply harder to predict - I may look into this is I have time.
- One of the main model benefits is rapid computation speed, which isn't so important for human proteins if pre-computed scores are available.

Together this means I wouldn't recomend replacing EVE if you have enough pre-calculated results since at best your results are likely to be similar. If you don't have EVE results for enough genes and a single method is useful I think the model could work, but I would benchmark performance for your use case before switching.
